In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
print(f"Number of Rows: {df.shape[0]}\nNumber of Columns: {df.shape[1]}")

Number of Rows: 891
Number of Columns: 12

In [4]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [5]:
df.tail(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [6]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
for i in df.columns:
    print(i)

PassengerId
Survived
Pclass
Name
Sex
Age
SibSp
Parch
Ticket
Fare
Cabin
Embarked

In [10]:
df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [11]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [12]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [13]:
def fillNaMean(df, categorical_cols):
    for col in categorical_cols:
        df[col] = df[col].fillna(df[col].mode()[0])

categorical_columns = ['Age','Cabin','Embarked']
fillNaMean(df, categorical_columns)

In [14]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [16]:
def changeFloattoInt64(cols):
    for i in cols:
       df[i] = df[i].astype('int64')

columns = ['Fare', 'Age']
changeFloattoInt64(columns)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    int64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    int64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: int64(7), object(5)
memory usage: 83.7+ KB

In [18]:
def encodeCols(cols):
    for i in cols:
        temp = pd.DataFrame({i:df[i].unique()})
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(temp))
        df[i] = data_LE.transform(df[i])

columns = ['Embarked', 'Cabin', 'Ticket','Sex','Name']
encodeCols(columns)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    int32
 4   Sex          891 non-null    int32
 5   Age          891 non-null    int64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    int32
 9   Fare         891 non-null    int64
 10  Cabin        891 non-null    int32
 11  Embarked     891 non-null    int32
dtypes: int32(5), int64(7)
memory usage: 66.3 KB

In [20]:
df.drop('PassengerId', axis=1, inplace=True)
df.drop('Name', axis=1, inplace=True)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int32
 3   Age       891 non-null    int64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Ticket    891 non-null    int32
 7   Fare      891 non-null    int64
 8   Cabin     891 non-null    int32
 9   Embarked  891 non-null    int32
dtypes: int32(4), int64(6)
memory usage: 55.8 KB

In [22]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [23]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [24]:
T = pd.read_csv("test.csv")
T

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [25]:
T.drop('PassengerId', axis=1, inplace=True)
T.drop('Name', axis=1, inplace=True)

In [26]:
T.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    418 non-null    int64
 1   Sex       418 non-null    object
 2   Age       332 non-null    float64
 3   SibSp     418 non-null    int64
 4   Parch     418 non-null    int64
 5   Ticket    418 non-null    object
 6   Fare      417 non-null    float64
 7   Cabin     91 non-null     object
 8   Embarked  418 non-null    object
dtypes: float64(2), int64(3), object(4)
memory usage: 29.5+ KB

In [27]:
def encodeCols(cols):
    for i in cols:
        temp = pd.DataFrame({i:T[i].unique()})
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(temp))
        T[i] = data_LE.transform(T[i])

columns = ['Embarked', 'Cabin', 'Ticket','Sex']
encodeCols(columns)

In [28]:
T.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    418 non-null    int64
 1   Sex       418 non-null    int32
 2   Age       332 non-null    float64
 3   SibSp     418 non-null    int64
 4   Parch     418 non-null    int64
 5   Ticket    418 non-null    int32
 6   Fare      417 non-null    float64
 7   Cabin     418 non-null    int32
 8   Embarked  418 non-null    int32
dtypes: float64(2), int32(4), int64(3)
memory usage: 23.0 KB

In [29]:
T.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    418 non-null    int64
 1   Sex       418 non-null    int32
 2   Age       332 non-null    float64
 3   SibSp     418 non-null    int64
 4   Parch     418 non-null    int64
 5   Ticket    418 non-null    int32
 6   Fare      417 non-null    float64
 7   Cabin     418 non-null    int32
 8   Embarked  418 non-null    int32
dtypes: float64(2), int32(4), int64(3)
memory usage: 23.0 KB

In [30]:
def fillNaMean(T, categorical_cols):
    for col in categorical_cols:
        T[col] = T[col].fillna(T[col].mode()[0])

categorical_columns = ['Fare','Age']
fillNaMean(T, categorical_columns)

In [31]:
T.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Cabin       0
Embarked    0
dtype: int64

In [32]:
def changeFloattoInt64(cols):
    for i in cols:
       T[i] = T[i].astype('int64')

columns = ['Fare', 'Age']
changeFloattoInt64(columns)

In [33]:
T.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    418 non-null    int64
 1   Sex       418 non-null    int32
 2   Age       418 non-null    int64
 3   SibSp     418 non-null    int64
 4   Parch     418 non-null    int64
 5   Ticket    418 non-null    int32
 6   Fare      418 non-null    int64
 7   Cabin     418 non-null    int32
 8   Embarked  418 non-null    int32
dtypes: int32(4), int64(5)
memory usage: 23.0 KB

In [34]:
Prediction = model.predict(T)

In [35]:
Prediction

array([ 0.16879284,  0.51559662,  0.17474995,  0.17169743,  0.64533816,
        0.22667309,  0.69061633,  0.28163795,  0.7975123 ,  0.11371034,
        0.19698035,  0.35235924,  0.89963309,  0.10094294,  0.78843691,
        0.846642  ,  0.32163641,  0.27778439,  0.60466967,  0.65113115,
        0.34270503,  0.23193749,  0.9820432 ,  0.54948101,  0.84228525,
       -0.00510571,  0.99258266,  0.27220016,  0.31031922,  0.20460422,
        0.13606731,  0.24314597,  0.55568813,  0.61067094,  0.46282394,
        0.29427867,  0.70249283,  0.70572306,  0.17958875,  0.24016326,
        0.15727874,  0.48778827,  0.07082429,  0.81389278,  0.82466803,
        0.15500364,  0.32479741,  0.22627039,  0.86573014,  0.5769176 ,
        0.40956656,  0.36444939,  0.76514733,  0.86597732,  0.39756715,
        0.11454514,  0.12203133,  0.16926199,  0.15286692,  0.99924976,
        0.21776677,  0.30207487,  0.21424988,  0.73309363,  0.50302239,
        0.83522035,  0.75491372,  0.38517477,  0.46929413,  0.74429296,
        0.71068398,  0.19710956,  0.66316346,  0.49003656,  1.03123852,
        0.54730685,  0.19434925,  0.67715125,  0.3100131 ,  0.7124929 ,
        0.30513826,  0.23154945,  0.36377413,  0.19620509,  0.39370745,
        0.2424218 ,  0.70762745,  0.70529094,  0.73002085,  0.40069431,
        0.6569883 ,  0.20046899,  0.80932502,  0.19086061,  0.5637407 ,
        0.17386817,  0.64537465,  0.13382959,  0.7042477 ,  0.12436666,
        0.87102147,  0.29486879,  0.22833773,  0.17254783,  0.75234112,
        0.15602416,  0.23789921,  0.22510751,  0.20158496,  0.36309019,
        0.32554971,  0.73880707,  0.87322598,  0.75568898,  0.7541482 ,
        0.25697794,  0.27796052,  0.73312383,  0.47614637,  0.74933411,
        0.88214206,  0.18684307,  0.92085372,  0.15194711,  0.22704564,
        0.70087018,  0.1897164 ,  0.65493793,  0.25049645,  0.18547831,
        0.11793445,  0.36004289,  0.63294159,  0.24021291,  0.07968324,
        0.17828952,  0.25373951,  0.33183319,  0.6676791 , -0.03839009,
        0.52519646,  1.01277024,  0.27175417,  0.32767821,  0.40157166,
        0.02944653,  0.50878363,  0.17390597,  0.51638556,  0.25840808,
        1.03209074,  0.26693083, -0.01641159,  0.58532772,  0.05632391,
        0.16330126,  0.98855198,  0.68839947,  0.37372515,  0.62135413,
        0.73816103,  0.302009  ,  0.83661733,  0.2005982 ,  0.25388412,
        0.62770048,  0.32033318,  0.08954422,  1.08590491,  0.68476294,
        0.17940791,  0.24750923,  0.15036699,  0.27920569, -0.01436054,
        0.86412702,  0.84953317,  0.31114203,  0.74285427,  0.79644115,
        0.31337254,  0.41873095,  0.97564336,  0.22368621,  0.98322935,
        0.25997366,  0.8148663 ,  0.1273656 ,  0.35461648,  0.25145739,
        0.2577173 ,  0.51858212,  0.18599403,  0.18303605,  0.39798564,
        0.13410426,  0.66167319,  0.71657905,  0.32017141,  0.6907348 ,
        0.7331342 ,  0.28070685,  0.41205802,  0.87622543,  0.30913216,
        0.55097966,  0.6502911 ,  0.33564827,  0.88109721,  0.17477263,
        0.1347209 ,  0.17721135,  0.37540028,  0.61821587,  0.41254983,
        0.31782285,  0.73906549,  0.30401182,  0.91759349,  0.2035231 ,
        0.8084958 ,  0.20132655,  0.81294288,  0.194913  ,  0.88033399,
        0.75195106,  0.18413217,  0.7278243 ,  0.08688679,  0.2792211 ,
        0.42353846,  1.01755185,  0.16341435,  0.23738237,  0.38793557,
        0.19933435,  0.31513541,  0.28401467,  0.81763354,  0.85758197,
        0.90986639,  0.70839267,  0.42959561,  0.19956453,  0.10937545,
        0.34326649,  0.82989454,  0.19253713,  0.7790522 ,  0.74371729,
        0.8774991 ,  0.18202033,  0.52134174,  0.17354416,  0.14204964,
        0.18457627,  0.22200649,  0.15668093,  0.86446576,  0.20033979,
        0.08417399,  0.19413775,  0.78256368,  0.74736036,  0.35429788,
        0.1963343 ,  0.50623488,  0.18444706,  0.68970113,  0.22534319,
        0.42288823,  0.22730406,  1.02796304,  0.69060586,  0.27894728,
        0.83279893,  0.28708189,  0.21581332,  0.24578996,  0.31593575,
        0.69520064,  0.23415896,  0.72976244,  0.79265287,  0.7424345 ,
        0.10714404,  0.17695294,  0.39301179,  0.27079308,  0.18763038,
        0.48399026,  0.67851759,  0.28088541,  0.19631138,  0.12087559,
        0.1706097 ,  0.94250067,  0.20460422,  0.47699417,  0.1552783 ,
        0.14007612,  0.39173155,  0.1964029 ,  0.1881917 ,  0.72653221,
        0.64000723,  0.38571503,  0.28566117,  0.22750545,  0.53121744,
        0.2202758 ,  0.27478434,  0.18315497,  0.64364495,  0.85688387,
        0.74473444,  0.29646201,  0.36240654,  0.16244128,  0.2537976 ,
        0.17228942,  0.25100542,  0.32641685,  0.45260501,  1.00164589,
        0.16643052,  0.82193212,  0.44178893,  0.28512163,  0.36078803,
        0.66745482,  0.35172358,  0.27817202,  0.73913631,  0.16476705,
        0.3975589 ,  0.30013673,  0.15025627,  0.3195174 ,  0.28140225,
        0.34744653,  0.13607063,  0.02391686,  0.97728116,  0.13273589,
        0.72529254,  0.33364212,  0.68879947,  0.34235561,  0.78209143,
        0.88352748,  0.30732323,  0.37007446,  0.16333079,  0.73143998,
        0.35075157,  0.66819523,  0.21817064,  0.22743327,  0.61183299,
       -0.10939832,  0.83667239,  0.78260826,  0.1727311 ,  1.02424483,
        0.52521236,  0.24035445,  0.71561094,  0.96155512,  0.35350396,
        0.3111178 ,  1.06416529,  0.27102688,  0.2353225 ,  0.69228106,
        1.03311428,  0.61818316,  0.35093275,  0.25483327,  0.09893042,
        0.22795011,  0.21152856,  0.69794746,  0.66558929,  0.32439797,
        0.79777162,  0.1794524 ,  0.1672498 ,  0.22859615,  0.14313075,
        0.44139402,  0.77805112,  0.20162832,  0.1926103 ,  0.0287303 ,
        0.94281693,  0.21016374,  0.82026531,  0.19410951,  0.19756198,
        0.95652075,  0.22476137,  1.08404883,  0.5485909 ,  0.40176713,
        0.3747073 ,  0.2993502 ,  0.416298  ,  0.73829024,  0.71947701,
        0.72950402,  0.90504523,  0.66241644,  0.18814722,  0.91718987,
        0.08693094,  0.19422004,  0.22931578])

In [36]:
Prediction = [1 if val >= 0.5 else 0 for val in Prediction]

T = pd.read_csv("gender_submission.csv")

T["Survived"] = Prediction[:len(T)]

T.to_csv("gender_submission.csv", index=False)

print("File updated successfully! ✅")

File updated successfully! ✅